[package]
name = "complex-iram"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"

[lib]
doctest = false

[features]
default = ["lapack"]
lapack = []
magma = []

[dependencies]
clap = { version = "4.5", features = ["derive"] }
num-complex = "0.4"
rand = { version = "0.10", features = ["std_rng"] }
lapack = "0.20"
# lapack-src = { version = "0.13", features = ["openblas"] }
# openblas-src = { version = "0.10", features = ["static"] }

[build-dependencies]
cc = "1"

[profile.release]
opt-level = 3
debug = false
strip = "symbols"
lto = "fat"
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = false
