[package]
name = "complex-block-cpu"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"

[lib]
doctest = false

[features]
default = []
track-memory = []

[dependencies]
clap = { version = "4.5", features = ["derive"] }
ndarray = "0.17"
num-complex = "0.4"
rand = { version = "0.10", features = ["std_rng"] }
lapack = "0.20"

[profile.release]
opt-level = 3
debug = false
strip = "symbols"
lto = "fat"
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = false
